# Site settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/custom.css" # Update this if you create a custom skin
locale: en-US
title: "Pasta Piracy - Open Source Recipes"
description: "Explore and share authentic Italian recipes, straight from the kitchen."
baseurl: "/pasta-piracy" # Leave empty if deploying to GitHub Pages at the root
url: "https://danetuso.github.io" # Update with your GitHub Pages URL
logo: "/assets/images/pasta_pirate_logo.webp" # Add your logo image path
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax:
  enable: false

google_fonts:
  - name: "Playfair Display"
    weights: "400,700"
  - name: "Lato"
    weights: "400,400i,700,700i"
# google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
# disqus:
  # shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: pastapiracy # site's Twitter username

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - markup.md
  - CHANGELOG.md
  - README.md
  - README-OLD.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Pasta Paolo
  picture: /assets/images/author.webp
  email:
  links:
    - title: Instagram
      url: https://instagram.com/pastapiracy
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/danetuso
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Instagram
    url: https://instagram.com/pastapiracy
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/danetuso
    icon: fab fa-github-square